=== DANCEcollaborative/bazaar/LlmPromptAgent/runtime/dialogues/TuTalkScenario.dtd
<!ELEMENT scenario (configuration,transitions,concepts,script)>
<!ATTLIST scenario
  scenario-name NMTOKEN #REQUIRED
  default-language NMTOKEN #REQUIRED>

<!-- MODULE CONFIGURATION -->
<!ELEMENT configuration (module*, dialogue-history?,dialogue-manager?,input?,
                         logger?,nlg?,nlu?,normalizer?,output?,
                         session-manager?,student-model?,
                         other-module*)>
<!ELEMENT dialogue-history EMPTY>
<!ATTLIST dialogue-history
  file NMTOKEN "DialogueHistory.py">


 <!ELEMENT module (param*)>
<!ATTLIST module
  name NMTOKEN #REQUIRED
  kind NMTOKEN #REQUIRED
  classname NMTOKENS #IMPLIED>
  

<!-- accept-initiative = no means the system does not accept any
     student initiative, yes means it does accept student initiative -->
<!-- remind = should allow something to be repeated to bring it back
     into focus -->
<!ELEMENT dialogue-manager EMPTY>
<!ATTLIST dialogue-manager
  file NMTOKEN "DialogueManager.py"
  accept-initiative (yes|no) "no"
  remind (yes|no) "yes">


<!ELEMENT input EMPTY>
<!ATTLIST input
  file NMTOKEN "Input.py">

<!ELEMENT logger EMPTY>
<!ATTLIST logger
  file NMTOKEN "Logger.py">

<!-- acknowledgement = indicates level at which acknowledgements 
     should be made.
       agree = only acknowledge utterances that the system can assess whether
               it agrees or disagrees with.
       understand = acknowledge that system understood (but not 
              whether agree/disagree with that content)
       hear = acknowledge whenever system believes it got a clear auditory input.
       none = disable acknowledgements
     topic-transition = indicates whether system should provide
     unscripted topic transitions or not.  Could be that the dialogue
     author wants to do his own.
-->
<!ELEMENT nlg EMPTY>
<!ATTLIST nlg
  file NMTOKEN "NLG.py"
  acknowledgement (agree|understand|hear|none) "agree"
  topic-transition (yes|no) "yes">
  
<!ELEMENT nlu EMPTY>
<!ATTLIST nlu
  file NMTOKEN "NLU.py"
  match-threshold NMTOKEN "0.8">

<!ELEMENT normalizer EMPTY>
<!ATTLIST normalizer
  file NMTOKEN "Normalizer.py">

<!ELEMENT output EMPTY>
<!ATTLIST output
  file NMTOKEN "Output.py">

<!ELEMENT session-manager EMPTY>
<!ATTLIST session-manager
  file NMTOKEN "SessionManager.py">

<!-- selection-policy applies if there are multiple choices for a goal.
       first =  pick first branch in list.
       least-difficult = pick least difficult branch first.
       most-difficult = pick most difficult branch first -->
<!-- phrase-difficulty-rankings = a list of numbers or symbols from least to
       most difficult, e.g. ynq whq whyq howq, for different ways to express
       a concept (typically a tutor question) -->
<!-- phrase-difficulty-neutral = sa number or symbol to use after coverage
       achieved e.g. inform -->
<!-- recipe-difficulty-rankings = a list of numbers or symbols from least to
       most difficult, e.g. 1 2 3 4 5 -->
<!-- recipe-difficulty-neutral = number or symbol to use after coverage
       achieved e.g. 0 -->
<!-- coverage-threshold applies only for selection-policy of least and
       most-difficult to guide when to move up or down the scale of difficulty.
       Coverage means how much of a goal the student was right about.
       coverage-threshold helps guide selection-policy -->
<!-- recency-threshold = how many seconds should elapse before assume
       something is no longer in focus/memory of hearer -->
<!-- topic-depth-threshold = how many topics can push to before may cause 
       to forget a topic-->
<!-- optional-step-policy is the policy for deciding when to skip a
       step that is marked as optional. All = consider recency and 
       coverage, recency = consider just recency, once = skip if it 
       ever is in the dialogue history, coverage = consider coverage
       only, and none = never skip an optional step -->
<!-- repeat-policy applies to retries on goals the student has
       already been exposed to.
       once = if branch has been done, then it should
              never be selected again for the given user.
       always = disregard previous usage in decision making
       covered = allow to repeat a branch if all other branches
	               have been tried at least once -->
<!ELEMENT student-model EMPTY>
<!ATTLIST student-model
  file NMTOKEN "StudentModel.py"
  selection-policy (first|least-difficult|most-difficult) "first"
  phrase-difficulty-rankings NMTOKENS "ynq whq whyq howq"
  phrase-difficulty-neutral NMTOKEN "inform"
  recipe-difficulty-rankings NMTOKENS "1 2 3 4 5"
  recipe-difficulty-neutral NMTOKEN "0"
  coverage-threshold NMTOKEN "0.8"
  recency-threshold NMTOKEN "20"
  topic-depth-threshold NMTOKEN "4"
  optional-step-policy (all|recency|once|coverage|none) "all"
  repeat-policy (always|once|covered) "once">

<!ELEMENT other-module EMPTY>
<!ATTLIST other-module
  name NMTOKEN #REQUIRED
  file NMTOKEN #REQUIRED
  settings NMTOKENS #IMPLIED>
  


<!-- TRANSITION PHRASES FOR ACKNOWLEDGEMENTS IN GENERATION MODULE -->
<!ELEMENT transitions (transition+)>
<!ELEMENT transition (tphrase+)>
<!ATTLIST transition 
   ack-type (agree|understand|hear|none) "none"
   ack-polarity (pos|neg) "pos"
   topic-status (new|interrupt|repeat|refresh|resume|finish|continue) "continue"
   floor-status (concede|grab|neutral) "grab"
   scope (immediate|nonimmediate|any) "any">
<!ELEMENT tphrase (#PCDATA)>
<!ATTLIST tphrase
   lang NMTOKEN #IMPLIED>
 
<!-- CONCEPT LIST -->
<!ELEMENT concepts (concept+)>
<!ELEMENT concept (phrase*)>
<!-- transition indicates whether a concept is a turn transition.  If 
     it is then signals to the NLG module that should override any 
     automatic transitions that it might issue -->
<!ATTLIST concept label NMTOKEN #REQUIRED
                  transition (yes|no) "no"
                  model NMTOKEN #IMPLIED
                  type NMTOKEN #IMPLIED>
<!ELEMENT phrase (#PCDATA)>
<!-- difficulty is a label or number that indicates the level
     of difficulty in how the concept is expressed relative to the student -->
<!-- lang is the natural language used in the concept (e.g. English) -->
<!-- flag settings are the special NLU services that need to be
     applied to interpret the concept (e.g. emoticon interpreter vs just
     straight NLU interpreter) -->
<!-- minimal indicates whether the phrase is a full phrase that can be
     used to say something to the student (no) or is a minimal phrase
     that captures a lot of different phrases (yes) and should not be
     used to say something to the student -->
<!ATTLIST phrase
  difficulty NMTOKEN #IMPLIED
  lang NMTOKEN #IMPLIED
  flag NMTOKEN #IMPLIED
  minimal (yes|no) "no">

<!-- difficulty is a label or number that indicates the difficulty level 
     of a goal -->
<!-- retry-until-cover is the conditions upon which to terminate a 
     retry of the goal.  The goal will be retried until all the 
     conditions indicated are met.  The only applicable attribute values 
     are the sem labels used in the script.  Warning: there is no
     validation of the conditions relative to the script so if a label
     does not appear in the script then a infinite loop may result.
     If no retry-until-cover condition is provided then the goal will
     not be retried -->
<!-- DIALOGUE SCRIPT -->
<!ELEMENT script (goal+)>
<!ELEMENT goal (step+)>
<!ATTLIST goal
  name NMTOKEN #REQUIRED
  difficulty NMTOKEN #IMPLIED
  sem NMTOKEN #IMPLIED
  retry-until-cover NMTOKENS #IMPLIED>
     
<!-- presence of answer element indicates that this initiation
     expects a multi-part response.  Signals to do additional
     processing -->
<!ELEMENT step ((initiation,response*) | subgoal)>
<!-- The attribute value of "said-once" for optional means that if
     the sem tag associated with the initiation was ever said then
     don't repeat it.  The attribute value of "yes" considers
     recency (see recency-threshold attribute in dialogue manager)
     while "no" means the the step will always be visited -->
<!ATTLIST step optional (said-once|yes|no) "no">

<!-- answer indicates that the initiation requires a multi-part response -->
<!-- see response element spec for comments on other attributes -->
<!ELEMENT initiation (#PCDATA)>
<!ATTLIST initiation
  necessary-and-sufficient-answer NMTOKENS #IMPLIED
  push NMTOKENS #IMPLIED
  push-nomatch NMTOKENS #IMPLIED
  sem NMTOKEN #IMPLIED
  say NMTOKENS #IMPLIED
  say-nomatch NMTOKENS #IMPLIED
  truth-val (yes|no|partial|unknown) "unknown">

<!-- the nomatch attributes below help implement multiple answer parts and 
     should only be used when multi-answer-expected has been set in 
     the initiation-->
<!-- push is what goal to push to if there is a match of the response 
     concept -->
<!-- push-nomatch is what to do if there is not a match -->
<!-- sem is a simple semantic label to mark content of the same 
     semantic meaning.  Keep separate from concept because the concept 
     in a different context may have different semantics -->
<!-- say is what to say before pushing if there is a match of a concept -->
<!-- say-nomatch is what to say before pushing for a nomatch of a concept -->
<!-- truth-val is whether the concept in this context is true or not
     or vague/partial or the truth value is irrelevant or simply
     unknown (unknown) -->
<!ELEMENT response (#PCDATA)>
<!ATTLIST response
  push NMTOKENS #IMPLIED
  push-nomatch NMTOKENS #IMPLIED
  sem NMTOKEN #IMPLIED
  say NMTOKENS #IMPLIED
  say-nomatch NMTOKENS #IMPLIED
  truth-val (yes|no|partial|unknown) "unknown">

<!-- allows a step in a goal to simply embed another goal -->
<!ELEMENT subgoal (#PCDATA)>
<!ATTLIST subgoal
  sem NMTOKEN #IMPLIED>

=== DANCEcollaborative/bazaar/MTurkLightSideLegacyAgent/runtime/dialogues/scenario-mouse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scenario SYSTEM "TuTalkScenario.dtd">
<scenario default-language="en" scenario-name="recorder_api">
	<configuration>
		
		<!-- It *is* possible to hook up a LightSide classifier to TuTalk, 
		such that the predicted labels are treated as concepts. 
		but not today. -->
			
		<!-- 	
		<module kind="model" name="animals"
			classname="edu.cmu.cs.lti.tutalk.module.SidePredictor">
			<param key="path" value="models/animals.ser" />
		</module> 
		-->

	</configuration>

	<!-- I'm not entirely sure what these are used for. -->
	<transitions>
		<transition ack-type="agree" floor-status="neutral">
			<tphrase> yes </tphrase>
			<tphrase> okay </tphrase>
		</transition>
	
		<transition ack-type="none">
			<tphrase> moving on... </tphrase>
		</transition>
	</transitions>
	
	<!-- 'Concepts' define things that students might say,
	     AND things that the tutor might say back. 
	     Tutor concepts should take the form of phrase lists.
		 Student concepts can be phrase lists, 
		 regular expressions, or lists of annotations,
	     but only one of these at a time. -->
		
	<concepts>
		<!-- this is a special kind of concept for catching unexpected student responses -->
		<concept label="unanticipated-response">
			<phrase>anything else</phrase>
		</concept>
		
		
		<!-- tutor concepts. -->
		<concept label="introduction">
			<phrase>A mouse is a small device used to point to and select items on your computer screen. 
               Although mice come in many shapes, the typical mouse does look a bit like an actual mouse. 
               It's small, oblong, and connected to the system unit by a long wire that resembles a tail. 
               Some newer mice are wireless.
            </phrase>
		</concept>

		<concept label="conclusion">
			<phrase>Okay - you can now continue discussing other parts.</phrase>
		</concept>
				
		<concept label="question1">
			<phrase>How many buttons a mouse has?</phrase>
		</concept>
		
		<!-- the tutor will choose randomly between multiple phrases for a concept. -->
		<concept label="question2">
			<phrase>When you move the mouse with your hand, what does appear on the screen?</phrase>
		</concept>
		
		<concept label="unrecognized">
			<phrase>I don't know what that is.</phrase>
			<phrase>That doesn't make sense to me.</phrase>
		</concept>
		
		<concept label="correct">
			<phrase>Well done!</phrase>
			<phrase>Okeydoke.</phrase>
			<phrase>Sounds good...</phrase>
		</concept>
		
		<concept label="ok">
			<phrase>Ok</phrase>
		</concept>
		
		<concept label="response1_1">
			<phrase>Well done! A mouse usually has two buttons: A primary button (usually the left button) and 
					a secondary button.
			</phrase>
		</concept>

		<concept label="response1_2">
			<phrase>Okeydoke. A mouse usually has two buttons: A primary button (usually the left button) and 
					a secondary button. Many mice also have a wheel between the two buttons, 
					which allows you to scroll smoothly through screens of information.
			</phrase>
		</concept>

		<concept label="response2">
			<phrase>Sounds good... When you move the mouse with your hand, 
					a pointer on your screen moves in the same direction. 
			</phrase>
		</concept>
		
		<concept label="correct_response1">
			<phrase>No! It's not correct. A mouse usually has two buttons: A primary button (usually the left button) and 
					a secondary button. Many mice also have a wheel between the two buttons, 
					which allows you to scroll smoothly through screens of information.
			</phrase>
		</concept>
		
	    <concept label="correct_response2">
			<phrase>No! It's not correct. When you move the mouse with your hand, 
					a pointer on your screen moves in the same direction. 
			</phrase>
		</concept>
	
		<!-- ent tutor concepts. -->
		
		
		<!-- student concepts. -->
		
		<!-- these match against external (MessageAnnotator) annotations. -->
		<concept label="yes" type="annotation">
			<phrase>AFFIRMATIVE</phrase>
		</concept>
		
		<concept label="no" type="annotation">
			<phrase>NEGATIVE</phrase>
		</concept>
		
		<!-- these match against regular expressions. -->

		<concept label="answer1_1" type="regex">
			<phrase>two|2</phrase>
		</concept>
					
		<concept label="answer1_2" type="regex">
			<phrase>three|3</phrase>
		</concept>
		
	    <concept label="answer2" type="regex">
			<phrase>pointer|arrow</phrase>
		</concept>
		
		<!-- end student concepts. -->
		
	</concepts>
	
	
	<script>
		<goal name="start" difficulty="1">
			
			<step>
				<!-- deliver a statement from the concept named "introduction"  -->
				<initiation>introduction</initiation>
			</step>
			
			<step>
				<!-- Every step begins with an initiating concept or literal phrase -->
				<initiation>question1</initiation>
				
				<!-- These are the "response" options. 
					If the concept between the tags matches the student statement, 
				    the "say" concept/phrase will be delivered by the tutor.
				    "push" adds another goal to the dialogue's stack. 
					 Note that goals should NOT be recursively nested. -->
					
				<response push="elicitate" say="response1_1">answer1_1</response>
				<response push="elicitate" say="response1_2">answer1_2</response>
				<response push="elicitate" say="correct_response1">unanticipated-response</response>
			</step>
			
			
			<step>
				<!-- Every step begins with an initiating concept or literal phrase -->
				<initiation>question2</initiation>
				
				<!-- These are the "response" options. 
					If the concept between the tags matches the student statement, 
				    the "say" concept/phrase will be delivered by the tutor.
				    "push" adds another goal to the dialogue's stack. 
					 Note that goals should NOT be recursively nested. -->
					
				<response push="elicitate" say="response2">answer2</response>
				<response push="elicitate" say="correct_response2">unanticipated-response</response>
			</step>
			
			<step>
				<initiation>conclusion</initiation>
			</step>
			
		</goal>
		

		<goal name="elicitate" difficulty="0">

			<step>
				<initiation>Let's move on.</initiation>

			</step>
		</goal>
	</script>

</scenario>

=== DANCEcollaborative/bazaar/MTurkLightSideLegacyAgent/runtime/dialogues/scenario-keyboard.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scenario SYSTEM "TuTalkScenario.dtd">
<scenario default-language="en" scenario-name="recorder_api">
	<configuration>
		
		<!-- It *is* possible to hook up a LightSide classifier to TuTalk, 
		such that the predicted labels are treated as concepts. 
		but not today. -->
			
		<!-- 	
		<module kind="model" name="animals"
			classname="edu.cmu.cs.lti.tutalk.module.SidePredictor">
			<param key="path" value="models/animals.ser" />
		</module> 
		-->

	</configuration>

	<!-- I'm not entirely sure what these are used for. -->
	<transitions>
		<transition ack-type="agree" floor-status="neutral">
			<tphrase> yes </tphrase>
			<tphrase> okay </tphrase>
		</transition>
	
		<transition ack-type="none">
			<tphrase> moving on... </tphrase>
		</transition>
	</transitions>
	
	<!-- 'Concepts' define things that students might say,
	     AND things that the tutor might say back. 
	     Tutor concepts should take the form of phrase lists.
		 Student concepts can be phrase lists, 
		 regular expressions, or lists of annotations,
	     but only one of these at a time. -->
		
	<concepts>
		<!-- this is a special kind of concept for catching unexpected student responses -->
		<concept label="unanticipated-response">
			<phrase>anything else</phrase>
		</concept>
		
		
		<!-- tutor concepts. -->
		<concept label="introduction">
			<phrase>A keyboard is used mainly for typing text into your computer. 
               		Like the keyboard on a typewriter, it has keys for letters and numbers, 
               		but it also has special keys. 
            </phrase>
		</concept>

		<concept label="conclusion">
			<phrase>Okay - you can now continue discussing other parts.</phrase>
		</concept>
				
		<concept label="question1">
			<phrase>Where are function keys on the keyboard?</phrase>
		</concept>
		
		<!-- the tutor will choose randomly between multiple phrases for a concept. -->
		<concept label="question2">
			<phrase>Where is numeric keypad on keyboard, if it is there?</phrase>
		</concept>
		
		<concept label="unrecognized">
			<phrase>I don't know what that is.</phrase>
			<phrase>That doesn't make sense to me.</phrase>
		</concept>
		
		<concept label="correct">
			<phrase>Well done!</phrase>
			<phrase>Okeydoke.</phrase>
			<phrase>Sounds good...</phrase>
		</concept>
		
		<concept label="ok">
			<phrase>Ok</phrase>
		</concept>
		
		<concept label="response1">
			<phrase>Well done! The function keys, found on the top row, 
			        perform different functions depending on where they are used.
			</phrase>
		</concept>


		<concept label="response2">
			<phrase>Sounds good... The numeric keypad, located on the right side of most keyboards, 
			 		allows you to enter numbers quickly. 
			</phrase>
		</concept>
		
		<concept label="correct_response1">
			<phrase>No! It's not correct. The function keys, found on the top row, 
			        perform different functions depending on where they are used.
			</phrase>
		</concept>
		
	    <concept label="correct_response2">
			<phrase>No! It's not correct. The numeric keypad, located on the right side of most keyboards, 
			 		allows you to enter numbers quickly. 
			</phrase>
		</concept>
	
		<!-- ent tutor concepts. -->
		
		
		<!-- student concepts. -->
		
		<!-- these match against external (MessageAnnotator) annotations. -->
		<concept label="yes" type="annotation">
			<phrase>AFFIRMATIVE</phrase>
		</concept>
		
		<concept label="no" type="annotation">
			<phrase>NEGATIVE</phrase>
		</concept>
		
		<!-- these match against regular expressions. -->

		<concept label="answer1" type="regex">
			<phrase>top</phrase>
		</concept>					
		
	    <concept label="answer2" type="regex">
			<phrase>right</phrase>
		</concept>
		
		<!-- end student concepts. -->
		
	</concepts>
	
	
	<script>
		<goal name="start" difficulty="1">
			
			<step>
				<!-- deliver a statement from the concept named "introduction"  -->
				<initiation>introduction</initiation>
			</step>
			
			<step>
				<!-- Every step begins with an initiating concept or literal phrase -->
				<initiation>question1</initiation>
				
				<!-- These are the "response" options. 
					If the concept between the tags matches the student statement, 
				    the "say" concept/phrase will be delivered by the tutor.
				    "push" adds another goal to the dialogue's stack. 
					 Note that goals should NOT be recursively nested. -->
					
				<response push="elicitate" say="response1">answer1</response>
				<response push="elicitate" say="correct_response1">unanticipated-response</response>
			</step>
			
			
			<step>
				<!-- Every step begins with an initiating concept or literal phrase -->
				<initiation>question2</initiation>
				
				<!-- These are the "response" options. 
					If the concept between the tags matches the student statement, 
				    the "say" concept/phrase will be delivered by the tutor.
				    "push" adds another goal to the dialogue's stack. 
					 Note that goals should NOT be recursively nested. -->
					
				<response push="elicitate" say="response2">answer2</response>
				<response push="elicitate" say="correct_response2">unanticipated-response</response>
			</step>
			
			<step>
				<initiation>conclusion</initiation>
			</step>
			
		</goal>
		
		<goal name="elicitate" difficulty="0">

			<step>
				<initiation>Let's move on.</initiation>

			</step>
		</goal>
		
	</script>

</scenario>

=== DANCEcollaborative/bazaar/MTurkLightSideLegacyAgent/runtime/dialogues/scenario-audio_encoding.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scenario SYSTEM "TuTalkScenario.dtd">
<scenario default-language="en" scenario-name="recorder_api">
	<configuration>
		
		<!-- It *is* possible to hook up a LightSide classifier to TuTalk, 
		such that the predicted labels are treated as concepts. 
		but not today. -->

	</configuration>

	<!-- I'm not entirely sure what these are used for. -->
	<transitions>
		<transition ack-type="agree" floor-status="neutral">
			<tphrase> yes </tphrase>
			<tphrase> okay </tphrase>
		</transition>
	
		<transition ack-type="none">
			<tphrase> moving on... </tphrase>
		</transition>
	</transitions>
	
	<!-- 'Concepts' define things that students might say,
	     AND things that the tutor might say back. 
	     Tutor concepts should take the form of phrase lists.
		 Student concepts can be phrase lists, 
		 regular expressions, or lists of annotations,
	     but only one of these at a time. -->
		
	<concepts>
		<!-- this is a special kind of concept for catching unexpected student responses -->
		<concept label="unanticipated-response">
			<phrase>anything else</phrase>
		</concept>
		
		
		<!-- tutor concepts. -->
		<concept label="introduction">
			<phrase>I can help you to decide the type of audio encoding to be used and example code snippet to do it.</phrase>
		</concept>
		
		<concept label="audio_encoding">
			<phrase>Do you know or decided on any audio encoding that can be used?</phrase>
		</concept>
		
		<!-- the tutor will choose randomly between multiple phrases for a concept. -->
		<concept label="facts">
			<phrase>You may probably want to use one of the following possible audio codecs
aac
aac_eld
amr_nb
amr_wb
default
he_aac
vorbis
			
			</phrase>
		</concept>
		
		<concept label="aac" type="regex">
			<phrase>aac-lc|low complexity</phrase>
		</concept>
		
		<concept label="aac_eld" type="regex">
			<phrase>aac_eld|aac-eld|enhanced low delay</phrase>
		</concept>
		
		<concept label="default" type="regex">
			<phrase>default</phrase>
		</concept>
	
			<concept label="amr_nb" type="regex">
			<phrase>amr_nb|narrowband</phrase>
		</concept>
		
				<concept label="amr_wb" type="regex">
			<phrase>amr_wb|amr wideband</phrase>
		</concept>
		
				<concept label="he_aac" type="regex">
			<phrase>he_aac|he-aac|high efficiency</phrase>
		</concept>
		
				<concept label="vorbis" type="regex">
			<phrase>vorbis|ogg</phrase>
		</concept>

		<concept label="unrecognized">
			<phrase>I don't know what that is.</phrase>
			<phrase>That doesn't make sense to me.</phrase>
		</concept>
		
		<concept label="correct">
			<phrase>Well done!</phrase>
			<phrase>Okeydoke.</phrase>
			<phrase>Sounds good...</phrase>
		</concept>
		
		<concept label="ok">
			<phrase>Ok</phrase>
		</concept>
		
		<concept label="aac_p" >
			<phrase>You can use AAC Low Complexity (AAC-LC) audio codec using following code snippet
			
			recorder_obj.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);
			
			</phrase>
		</concept>
		
		<concept label="aac_eld_p" >
			<phrase>You can use Enhanced Low Delay AAC (AAC-ELD) audio codec using following code snippet
			
			recorder_obj.setAudioEncoder(MediaRecorder.AudioEncoder.AAC_ELD);
			
			</phrase>
		</concept>
		
		<concept label="default_p" >
			<phrase>You can use default audio codec using following code snippet
			
			recorder_obj.setAudioEncoder(MediaRecorder.AudioEncoder.DEFAULT);
			
			</phrase>
		</concept>
	
			<concept label="amr_nb_p" >
			<phrase>You can use AMR (Narrowband) audio codec using following code snippet
			
			recorder_obj.setAudioEncoder(MediaRecorder.AudioEncoder.AMR_NB);
			
			</phrase>
		</concept>
		
				<concept label="amr_wb_p" >
			<phrase>You can use AMR (Wideband) audio codec using following code snippet
			
			recorder_obj.setAudioEncoder(MediaRecorder.AudioEncoder.AMR_WB);
			
			</phrase>
		</concept>
		
				<concept label="he_aac_p" >
			<phrase>You can use High Efficiency AAC (HE-AAC) audio codec using following code snippet
			
			recorder_obj.setAudioEncoder(MediaRecorder.AudioEncoder.HE_AAC);
			
			</phrase>
		</concept>
		
				<concept label="vorbis_p" >
			<phrase>You can use Ogg Vorbis audio codec using following code snippet
			
			recorder_obj.setAudioEncoder(MediaRecorder.AudioEncoder.VORBIS);
			
			</phrase>
		</concept>
		
		<concept label="congrats">
			<phrase>You're ready to be a zoologist!</phrase>
		</concept>
		
		<concept label="dont_be_clever">
			<phrase>Aren't you clever?</phrase>
		</concept>
		
		<!-- ent tutor concepts. -->
		
		
		<!-- student concepts. -->
		
		<!-- these match against external (MessageAnnotator) annotations. -->
		<concept label="yes" type="annotation">
			<phrase>AFFIRMATIVE</phrase>
		</concept>
		
		<concept label="no" type="annotation">
			<phrase>NEGATIVE</phrase>
		</concept>
		
		<!-- these match against regular expressions. -->
		
		<concept label="audiorecord" type="regex">
			<phrase>audiorecord</phrase>
		</concept>
		
		
		<concept label="mediarecorder" type="regex">
			<phrase>mediarecorder</phrase>
		</concept>
		
		<concept label="mammal" type="regex">
			<phrase>mammal|cow|dog|cat|human|gerbil|whale|elephant</phrase>
			<phrase>fur|hair|milk|warm</phrase>
		</concept>
		
		<!-- end student concepts. -->
		
	</concepts>
	
	
	<script>
		<goal name="start" difficulty="1">
			
			<step>
				<!-- deliver a statement from the concept named "introduction"  -->
				<initiation>introduction</initiation>
			</step>
			
			<step>
				<!-- Every step begins with an initating concept or literal phrase -->
				<initiation>audio_encoding</initiation>
				
				<!-- These are the "response" options. 
					If the concept between the tags matches the student statement, 
				    the "say" concept/phrase will be delivered by the tutor.
				    "push" adds another goal to the dialogue's stack. 
					 Note that goals should NOT be recursively nested. -->
					
				<response push="elicitate" say="ok">yes</response>
				<response push="remediate" say="ok">no</response>
                
				<!-- unanticipated-response is special: it's anything that doesn't match one of the above. -->
				<response push="remediate" say="ok">unanticipated-response</response>
			</step>
			
			
			<step>
				<initiation>Ok, move on.</initiation>
			</step>
		</goal>
		
		<!-- Goals are referenced by their names. "difficulty" is meaningless for now. -->
		<goal name="remediate" difficulty="0">
			<step>
				<initiation>Maybe this will help:</initiation>
			</step>
			<step>
				<!-- deliver a statement from the concept named "facts"  -->
				<initiation>facts</initiation>
			</step>

			<step>
				<initiation>Which one you will like to choose?</initiation>
                <response say="amr_wb_p">amr_wb</response>
                <response say="amr_nb_p">amr_nb</response>
				<response say="default_p">default</response>
				<response say="aac_p">aac</response>
                <response say="aac_eld_p">aac_eld</response>
				<response say="he_aac_p">he_aac</response>
				<response say="vorbis_p">vorbis</response>
				<response say="unrecognized">unanticipated-response</response>
			</step>
		</goal>
		
	   <goal name="elicitate" difficulty="0">

			<step>
				<initiation>Which codec you will use?</initiation>
                <response say="amr_wb_p">amr_wb</response>
                <response say="amr_nb_p">amr_nb</response>
				<response say="default_p">default</response>
				<response say="unrecognized">unanticipated-response</response>
			</step>
		</goal>
		
	</script>

</scenario>
